name: nomirrorsmap
version: 1.0.24
author: jrote1<jrote1@me.com>
description: A library for mapping without mirrors this includes JSON and Object to Object
homepage: https://github.com/jrote1/nomirrorsmap.dart
environment:
  sdk: '>=1.9.0 <2.0.0'
dependencies:
  code_transformers: any
  dart_style: any
  path: '>=1.0.0 <2.0.0'
  reflective: '^0.0.23'
dev_dependencies:
  test: any
  transformer_test: any
